// src/controllers/dispatchController.js
import { prisma } from '../lib/prisma.js';
import { findPickingStrategy } from '../utils/pickingEngine.js';
import { executeStockMove } from '../services/stockService.js';

export const validate = (schema) => (req, res, next) => {
    try {
        schema.parse(req.body); // This validates the data
        next(); // If valid, proceed to controller
    } catch (error) {
        return res.status(400).json({
            success: false,
            message: "Validation Error",
            details: error.errors
        });
    }
};

export const processDispatch = async (req, res) => {
    const { salesOrderId } = req.body;

    try {
        const result = await prisma.$transaction(async (tx) => {
            // 1. Get the order
            const order = await tx.salesOrder.findUnique({
                where: { id: salesOrderId },
                include: { items: { include: { productVariant: true } } }
            });

            if (!order) throw new Error("Order not found.");
            if (order.status === 'DISPATCHED') throw new Error("Order already dispatched.");

            // 2. Process each item using the Picking Engine
            for (const item of order.items) {
                // A. Use the Engine to decide where to pull stock from (FEFO/FIFO)
                const pickingInstructions = await findPickingStrategy(tx, {
                    productVariantId: item.productVariantId,
                    quantity: item.quantityCount
                });

                // B. Execute the movement for every instruction generated by the engine
                for (const instruction of pickingInstructions) {
                    await executeStockMove(tx, {
                        sourceBinId: instruction.binId, // From Picking Engine
                        destBinId: null,               // Outbound (Customer)
                        productVariantId: item.productVariantId,
                        batchId: instruction.batchId,
                        weight: item.quantityKg,       // Assuming kg calculation
                        volume: 0,                     // Optional: calculate volume
                        quantity: instruction.quantity,
                        type: 'SALES_OUTBOUND',
                        reference: `OrderRef: ${order.orderRef}`,
                        notes: `Dispatching Batch: ${instruction.batchNumber}`
                    });
                }
            }

            // 3. Update Order status
            return await tx.salesOrder.update({
                where: { id: salesOrderId },
                data: { status: 'DISPATCHED' }
            });
        });

        return res.status(200).json({ success: true, message: "Dispatch successful!", data: result });
    } catch (error) {
        console.error("Dispatch Error:", error);
        return res.status(500).json({ success: false, message: error.message });
    }
};